// Karteikarten-Datenbank für den Lernmodus
// Erstellt aus "Zusammenfassung SBR anhand Leitfaden Repetitorium 2025"
//
// Anderes Format als questions.js (freies Erinnern statt Multiple-Choice-Wiedererkennen):
// front = Begriff/Frage, back = kurze Antwort/Definition.

window.FLASHCARDS = [

  // ===================== 1.1 Pädagogik und Recht =====================
  { id: "fc-sr-1.1-01", part: "Schulrecht", chapter: "1.1 Pädagogik und Recht",
    front: "Die 3 Schritte der juristischen Fallbearbeitung?",
    back: "1. Feststellung des Sachverhalts, 2. Zuordnung zum gesetzlichen Tatbestand (Subsumtion), 3. Auswahl der Rechtsfolge (gebunden oder Ermessen)." },
  { id: "fc-sr-1.1-02", part: "Schulrecht", chapter: "1.1 Pädagogik und Recht",
    front: "Was bedeuten \"kann\" / \"braucht nicht\"?",
    back: "Ermessen der Behörde." },
  { id: "fc-sr-1.1-03", part: "Schulrecht", chapter: "1.1 Pädagogik und Recht",
    front: "Was bedeuten \"muss\", \"hat zu\", \"ist\", \"darf nicht\"?",
    back: "Gebundene Entscheidung, kein Ermessensspielraum, keine Abweichung möglich." },
  { id: "fc-sr-1.1-04", part: "Schulrecht", chapter: "1.1 Pädagogik und Recht",
    front: "Unterschied \"im Einvernehmen mit\" vs. \"im Benehmen mit\"?",
    back: "Einvernehmen: vorheriges Einverständnis der anderen Stelle nötig. Benehmen: nur Gelegenheit zur Stellungnahme geben." },
  { id: "fc-sr-1.1-05", part: "Schulrecht", chapter: "1.1 Pädagogik und Recht",
    front: "Nenne die 4 Ermessensfehler.",
    back: "Ermessensnichtgebrauch (keine Einzelfallprüfung), Ermessensmissbrauch (sachfremde Erwägungen), Ermessensüberschreitung (Rechtsfolge außerhalb des Rahmens), Unverhältnismäßigkeit (zu milde/streng)." },

  // ===================== 1.2 Erziehungs- und Bildungsauftrag =====================
  { id: "fc-sr-1.2-01", part: "Schulrecht", chapter: "1.2 Erziehungs- und Bildungsauftrag",
    front: "Wo ist der Erziehungs- und Bildungsauftrag der Schule verfassungsrechtlich verankert?",
    back: "Grundgesetz Art. 6, Landesverfassung BW Art. 12, SchG § 1." },
  { id: "fc-sr-1.2-02", part: "Schulrecht", chapter: "1.2 Erziehungs- und Bildungsauftrag",
    front: "Nenne zwei in der Landesverfassung genannte Erziehungswerte.",
    back: "U.a. \"Geist christlicher Nächstenliebe\", \"Menschlichkeit und Friedensliebe\", \"Achtung der Würde und Überzeugung anderer\"." },
  { id: "fc-sr-1.2-03", part: "Schulrecht", chapter: "1.2 Erziehungs- und Bildungsauftrag",
    front: "Kann der Staat in der Schule eigene, von den Eltern unabhängige Erziehungsziele verfolgen?",
    back: "Ja, laut Bundesverfassungsgericht." },

  // ===================== 1.3 Rechtsquellen im Schulrecht =====================
  { id: "fc-sr-1.3-01", part: "Schulrecht", chapter: "1.3 Rechtsquellen im Schulrecht",
    front: "Normenpyramide des Schulrechts (von oben nach unten)?",
    back: "Landesverfassung → Gesetze (z.B. SchG) → Rechtsverordnungen (z.B. NVO) → Verwaltungsvorschriften/Erlasse." },
  { id: "fc-sr-1.3-02", part: "Schulrecht", chapter: "1.3 Rechtsquellen im Schulrecht",
    front: "Wer erlässt das Schulgesetz (SchG)?",
    back: "Der Landtag BW (Legislative)." },
  { id: "fc-sr-1.3-03", part: "Schulrecht", chapter: "1.3 Rechtsquellen im Schulrecht",
    front: "Wer erlässt Rechtsverordnungen wie die NVO?",
    back: "Das Kultusministerium, aufgrund gesetzlicher Ermächtigung." },
  { id: "fc-sr-1.3-04", part: "Schulrecht", chapter: "1.3 Rechtsquellen im Schulrecht",
    front: "Wer erlässt Erlasse (z.B. Abiturerlass)?",
    back: "Die Regierungspräsidien." },
  { id: "fc-sr-1.3-05", part: "Schulrecht", chapter: "1.3 Rechtsquellen im Schulrecht",
    front: "Sind KMK-Beschlüsse unmittelbar geltendes Recht?",
    back: "Nein, sie müssen von jedem Land einzeln bewertet/umgesetzt werden (Kulturhoheit der Länder, GG Art. 70)." },
  { id: "fc-sr-1.3-06", part: "Schulrecht", chapter: "1.3 Rechtsquellen im Schulrecht",
    front: "Wer trifft \"wesentliche Entscheidungen\" (z.B. Bildungspläne)?",
    back: "Der Gesetzgeber selbst – nicht die Verwaltung." },

  // ===================== 1.4 Gliederung des Schulwesens =====================
  { id: "fc-sr-1.4-01", part: "Schulrecht", chapter: "1.4 Gliederung des Schulwesens in BW",
    front: "Wie viele Schularten gibt es in BW insgesamt?",
    back: "12 (für die Prüfung mind. 5 nennen: GS, HS/WRS, RS, Gymnasium, GMS, SBBZ)." },
  { id: "fc-sr-1.4-02", part: "Schulrecht", chapter: "1.4 Gliederung des Schulwesens in BW",
    front: "Pflichtschulen (fester Schulbezirk) vs. Wahlschulen?",
    back: "Pflicht: Grundschule, Berufsschule, SBBZ. Wahl (kein fester Bezirk): HS, WRS, RS, GMS, Gymnasium, Berufsfach-/Berufskolleg." },
  { id: "fc-sr-1.4-03", part: "Schulrecht", chapter: "1.4 Gliederung des Schulwesens in BW",
    front: "\"2 aus 3\"-Regel bei der Grundschulempfehlung?",
    back: "Empfehlung der Klassenkonferenz, Kompass 4, Elternwunsch – stimmen weder 1. noch 2. mit dem Elternwunsch überein, ist ein Potentialtest möglich." },
  { id: "fc-sr-1.4-04", part: "Schulrecht", chapter: "1.4 Gliederung des Schulwesens in BW",
    front: "Welche Schulart unterrichtet zusätzlich zum Gymnasium auch Kinder mit Gymnasialempfehlung?",
    back: "Die Gemeinschaftsschule (GMS)." },
  { id: "fc-sr-1.4-05", part: "Schulrecht", chapter: "1.4 Gliederung des Schulwesens in BW",
    front: "Ersatzschule vs. Ergänzungsschule?",
    back: "Ersatzschule ersetzt eine öffentliche Schule und erfüllt die Schulpflicht (z.B. Waldorfschule). Ergänzungsschule nicht (z.B. Sprachschule)." },
  { id: "fc-sr-1.4-06", part: "Schulrecht", chapter: "1.4 Gliederung des Schulwesens in BW",
    front: "Bis zu welchem Lebensjahr besteht Schulpflicht?",
    back: "Bis zum 18. Lebensjahr." },

  // ===================== 1.5 Schulträger, Lernmittelfreiheit =====================
  { id: "fc-sr-1.5-01", part: "Schulrecht", chapter: "1.5 Schulträger, Lernmittelfreiheit",
    front: "Wer ist Schulträger (Sachkostenträger)?",
    back: "In der Regel die Gemeinde (bei ELGS: die Schulstiftung)." },
  { id: "fc-sr-1.5-02", part: "Schulrecht", chapter: "1.5 Schulträger, Lernmittelfreiheit",
    front: "Wer trägt die Personalkosten der Lehrkräfte?",
    back: "Das Land BW als Dienstherr." },
  { id: "fc-sr-1.5-03", part: "Schulrecht", chapter: "1.5 Schulträger, Lernmittelfreiheit",
    front: "Wann wird ein Lernmittel \"notwendig\" (= lernmittelfrei)?",
    back: "Wenn eine Fachlehrkraft es zum verpflichtenden Unterrichtsgegenstand macht (z.B. Taschenrechner, Ganzschriften)." },
  { id: "fc-sr-1.5-04", part: "Schulrecht", chapter: "1.5 Schulträger, Lernmittelfreiheit",
    front: "Geringfügigkeitsgrenze bei Lernmitteln?",
    back: "Ca. 1 Euro (Ausnahme: Privatschulen dürfen selbst entscheiden)." },
  { id: "fc-sr-1.5-05", part: "Schulrecht", chapter: "1.5 Schulträger, Lernmittelfreiheit",
    front: "Ist eine verpflichtende Kopierpauschale zulässig?",
    back: "Nein, nur auf freiwilliger Basis (verstößt sonst gegen die Schulgeldfreiheit)." },
  { id: "fc-sr-1.5-06", part: "Schulrecht", chapter: "1.5 Schulträger, Lernmittelfreiheit",
    front: "Haben Lehrkräfte Weisungsbefugnis gegenüber Sekretariat/Hausmeister?",
    back: "Nein, keine generelle Weisungsbefugnis. Der/die Schulleiter*in hingegen schon (bzgl. Schulbetrieb/Ordnung)." },

  // ===================== 1.6 Schulaufsicht =====================
  { id: "fc-sr-1.6-01", part: "Schulrecht", chapter: "1.6 Schulaufsicht",
    front: "Rechtsgrundlage der staatlichen Schulaufsicht?",
    back: "GG Art. 7: \"Das gesamte Schulwesen steht unter der Aufsicht des Staates.\"" },
  { id: "fc-sr-1.6-02", part: "Schulrecht", chapter: "1.6 Schulaufsicht",
    front: "Oberste Schulaufsichtsbehörde – zuständig für Gymnasien?",
    back: "Das Kultusministerium (Rechtsverordnungen, Bildungspläne, Versetzungs-/Prüfungsordnungen)." },
  { id: "fc-sr-1.6-03", part: "Schulrecht", chapter: "1.6 Schulaufsicht",
    front: "Obere Schulaufsichtsbehörde – zuständig für Gymnasien?",
    back: "Die 4 Regierungspräsidien (Fachaufsicht über Schulen, Dienstaufsicht über Lehrkräfte/Schulleiter)." },
  { id: "fc-sr-1.6-04", part: "Schulrecht", chapter: "1.6 Schulaufsicht",
    front: "Untere Schulaufsichtsbehörde – wofür NICHT zuständig?",
    back: "Nicht für Gymnasien und berufliche Schulen (dort: RP). Zuständig für GS, HS/WRS, RS." },
  { id: "fc-sr-1.6-05", part: "Schulrecht", chapter: "1.6 Schulaufsicht",
    front: "Wer hat bei Schulen in freier Trägerschaft (z.B. ELGS) die Dienstaufsicht?",
    back: "Der Träger (z.B. die Schulstiftung), nicht der Staat." },
  { id: "fc-sr-1.6-06", part: "Schulrecht", chapter: "1.6 Schulaufsicht",
    front: "Grenze der Schulaufsicht bei der Unterrichtsmethode?",
    back: "Methodenfreiheit der Lehrkräfte – die Schulaufsicht darf keine konkrete Methode vorschreiben." },
  { id: "fc-sr-1.6-07", part: "Schulrecht", chapter: "1.6 Schulaufsicht",
    front: "IBBW vs. ZSL?",
    back: "IBBW: Statistik, Kompetenzmessung (VERA 8), Bildungsforschung. ZSL: Aus-/Fortbildung, Fachberater, Bildungspläne, Personalentwicklung." },

  // ===================== 1.7 Verwaltungsakte, Widerspruch =====================
  { id: "fc-sr-1.7-01", part: "Schulrecht", chapter: "1.7 Verwaltungsakte, Widerspruch",
    front: "Verwaltungsakt vs. einfaches Verwaltungshandeln?",
    back: "Verwaltungsakt: Einzelfallregelung mit unmittelbarer Rechtswirkung nach außen, betrifft Grundverhältnis (z.B. Nichtversetzung). Verwaltungshandeln: geringe Tragweite, Betriebsverhältnis (z.B. Umsetzen im Klassenzimmer)." },
  { id: "fc-sr-1.7-02", part: "Schulrecht", chapter: "1.7 Verwaltungsakte, Widerspruch",
    front: "Rechtsmittel gegen Verwaltungshandeln vs. Verwaltungsakt?",
    back: "Verwaltungshandeln: formlose Beschwerde. Verwaltungsakt: förmlicher Widerspruch." },
  { id: "fc-sr-1.7-03", part: "Schulrecht", chapter: "1.7 Verwaltungsakte, Widerspruch",
    front: "Widerspruchsfrist gegen einen Verwaltungsakt?",
    back: "In der Regel 1 Monat; ohne Rechtsmittelbelehrung (z.B. Zeugnis) 1 Jahr." },
  { id: "fc-sr-1.7-04", part: "Schulrecht", chapter: "1.7 Verwaltungsakte, Widerspruch",
    front: "Hat ein Widerspruch gegen § 90-Maßnahmen aufschiebende Wirkung?",
    back: "Nein, ausnahmsweise nicht." },
  { id: "fc-sr-1.7-05", part: "Schulrecht", chapter: "1.7 Verwaltungsakte, Widerspruch",
    front: "Wo wird ein Widerspruch gegen einen schulischen Verwaltungsakt eingelegt?",
    back: "Bei der Schule oder beim Regierungspräsidium (Widerspruchsbehörde)." },

  // ===================== 1.8 Schulverfassung, Konferenzen =====================
  { id: "fc-sr-1.8-01", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Was regelt die \"Schulverfassung\"?",
    back: "Welche Personen/Gremien an der Schule für welche Aufgaben zuständig sind (§§ 41-47 SchG)." },
  { id: "fc-sr-1.8-02", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Warum gibt es keine Dienstordnung für Schulleiter in BW?",
    back: "Damit ein Ermessensspielraum für eigenverantwortliche Entscheidungen des SL bleibt." },
  { id: "fc-sr-1.8-03", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Welches Gremium ist das \"gemeinsame Organ der Schule\"?",
    back: "Die Schulkonferenz (§ 47 SchG)." },
  { id: "fc-sr-1.8-04", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Vorsitz der Schulkonferenz?",
    back: "Schulleiter*in (Vorsitz), Elternbeiratsvorsitzende*r (stv. Vorsitz); je 3 gewählte Lehrkräfte/Eltern/Schüler." },
  { id: "fc-sr-1.8-05", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Wie oft muss die Schulkonferenz mindestens tagen?",
    back: "Mindestens einmal pro Halbjahr." },
  { id: "fc-sr-1.8-06", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Dürfen Referendare in der Schulkonferenz stimmberechtigt mitwirken?",
    back: "Nein (in GLK/Fach-/Klassenkonferenz nur mit beratender Stimme)." },
  { id: "fc-sr-1.8-07", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Was gilt für rechtswidrige Konferenzbeschlüsse?",
    back: "Nicht bindend; die Schulleitung darf sie nicht umsetzen und kann die Schulaufsicht einschalten." },
  { id: "fc-sr-1.8-08", part: "Schulrecht", chapter: "1.8 Schulverfassung, Konferenzen",
    front: "Wofür steht SMV?",
    back: "Schüler mit Verantwortung." },

  // ===================== 1.9 Rechtsstellung SuS, Schulpflicht =====================
  { id: "fc-sr-1.9-01", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Was umfasst die Schulpflicht?",
    back: "Verhaltenspflicht (Schulordnung einhalten) + Schulbesuchspflicht (regelmäßige Teilnahme)." },
  { id: "fc-sr-1.9-02", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Wer ist für die Erfüllung der Schulpflicht verantwortlich?",
    back: "Die Erziehungsberechtigten." },
  { id: "fc-sr-1.9-03", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Maßnahme gegenüber dem Schüler bei Nichterfüllung der Schulpflicht?",
    back: "Schulzwang durch die Polizeibehörde (gegenüber Eltern: Ordnungswidrigkeit/Zwangsgeld)." },
  { id: "fc-sr-1.9-04", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Entschuldigungsfrist bei Verhinderung?",
    back: "Spätestens am 3. Tag nach der Verhinderung (schriftlich/elektronisch)." },
  { id: "fc-sr-1.9-05", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Ab wann Selbstentschuldigungsrecht?",
    back: "Ab Volljährigkeit (18 Jahre)." },
  { id: "fc-sr-1.9-06", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Ab welchem Alter keine Abmeldung vom Religionsunterricht mehr gegen den Willen des Kindes?",
    back: "Ab 12 Jahren. Ab 14 Jahren (Religionsmündigkeit) entscheidet der/die Schüler*in selbst." },
  { id: "fc-sr-1.9-07", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Auffangfach bei Abmeldung vom Religionsunterricht?",
    back: "Ethik (ab Kl. 5/6)." },
  { id: "fc-sr-1.9-08", part: "Schulrecht", chapter: "1.9 Rechtsstellung SuS, Schulpflicht",
    front: "Darf die Schulleitung Schülerzeitschriften inhaltlich zensieren?",
    back: "Nein – nur den Vertrieb bei Gesetzesverstößen verbieten (Presse-/Meinungsfreiheit, Zensurverbot)." },

  // ===================== 1.10 Mitwirkung der Eltern =====================
  { id: "fc-sr-1.10-01", part: "Schulrecht", chapter: "1.10 Mitwirkung der Eltern",
    front: "Was bedeutet \"Dualität des Erziehungsauftrags\"?",
    back: "Eltern und Schule sind bei der Erziehung gleichgestellt (GG Art. 6, LV Art. 12)." },
  { id: "fc-sr-1.10-02", part: "Schulrecht", chapter: "1.10 Mitwirkung der Eltern",
    front: "Elternrechte bei Volljährigkeit des Schülers?",
    back: "Kollektive Elternrechte bleiben, Individualrechte (Entscheidung/Information) erlöschen grundsätzlich." },
  { id: "fc-sr-1.10-03", part: "Schulrecht", chapter: "1.10 Mitwirkung der Eltern",
    front: "Was ist die Klassenpflegschaft?",
    back: "Zusammenwirken von Eltern und Lehrern einer Klasse (Elternabend), Vorsitz: Klassenelternvertreter*in." },
  { id: "fc-sr-1.10-04", part: "Schulrecht", chapter: "1.10 Mitwirkung der Eltern",
    front: "Formalisierte Rechte des Elternbeirats?",
    back: "Nur Informations- und Anhörungsrecht, keine Entscheidungs-/Mitbestimmungsrechte." },
  { id: "fc-sr-1.10-05", part: "Schulrecht", chapter: "1.10 Mitwirkung der Eltern",
    front: "3 Kategorien der Elternrechte?",
    back: "Individualrechte (eigenes Kind), kollektive Rechte (Klassenpflegschaft), repräsentative Rechte (Elternbeirat)." },
  { id: "fc-sr-1.10-06", part: "Schulrecht", chapter: "1.10 Mitwirkung der Eltern",
    front: "Beispiel für eine Grenze der Elternrechte?",
    back: "Religiöse Bedenken gegen Schwimmunterricht rechtfertigen keine automatische Befreiung." },

  // ===================== 1.11 Erziehungs- und Ordnungsmaßnahmen =====================
  { id: "fc-sr-1.11-01", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Rechtsgrundlage für präventive/pädagogische Erziehungsmaßnahmen?",
    back: "§ 23 SchG." },
  { id: "fc-sr-1.11-02", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Rechtsgrundlage für Erziehungs- und Ordnungsmaßnahmen (EOM)?",
    back: "§ 90 SchG." },
  { id: "fc-sr-1.11-03", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Voraussetzung für § 90 SchG?",
    back: "Schweres oder wiederholtes Fehlverhalten, wenn pädagogische Erziehungsmaßnahmen nicht (mehr) ausreichen." },
  { id: "fc-sr-1.11-04", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Maximale Dauer Unterrichtsausschluss nach § 90?",
    back: "Bis zu 4 Wochen." },
  { id: "fc-sr-1.11-05", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Wer entscheidet über einen Schulausschluss?",
    back: "Der/die Schulleiter*in." },
  { id: "fc-sr-1.11-06", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Grundsätze des § 90 SchG (5 Stück)?",
    back: "Anhörungsrecht, Einzelfallprüfung (Geeignetheit/Erforderlichkeit), Schulbezug, keine Mehrfachbestrafung, keine Kollektivstrafen." },
  { id: "fc-sr-1.11-07", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Mittelbarer Schulbezug – Beispiel?",
    back: "Beleidigung in einer WhatsApp-Gruppe, die geeignet ist, den schulischen Frieden zu stören." },
  { id: "fc-sr-1.11-08", part: "Schulrecht", chapter: "1.11 Erziehungs- und Ordnungsmaßnahmen",
    front: "Ist körperliche Züchtigung erlaubt?",
    back: "Nein, nur ausnahmsweise zur Gefahrenabwehr/Notwehr." },

  // ===================== 1.12 Aufsichtspflicht =====================
  { id: "fc-sr-1.12-01", part: "Schulrecht", chapter: "1.12 Aufsichtspflicht",
    front: "Rechtliche Grundlage der Aufsichtspflicht in BW?",
    back: "Keine direkte gesetzliche Regelung – logische Folge der Schulpflicht." },
  { id: "fc-sr-1.12-02", part: "Schulrecht", chapter: "1.12 Aufsichtspflicht",
    front: "Aufsichtspflicht auf dem Schulweg?",
    back: "Nein (auf Unterrichtswegen wie Schule–Schwimmbad dagegen ja)." },
  { id: "fc-sr-1.12-03", part: "Schulrecht", chapter: "1.12 Aufsichtspflicht",
    front: "Gilt Aufsichtspflicht für volljährige Schüler*innen?",
    back: "Nein, aber allgemeine Fürsorgepflicht bleibt." },
  { id: "fc-sr-1.12-04", part: "Schulrecht", chapter: "1.12 Aufsichtspflicht",
    front: "Aufsichtspflicht vor/nach dem Unterricht?",
    back: "Ca. 10-15 Minuten erweitert." },
  { id: "fc-sr-1.12-05", part: "Schulrecht", chapter: "1.12 Aufsichtspflicht",
    front: "3 Prinzipien der Aufsichtsführung?",
    back: "Vorausschauende Umsicht, ununterbrochene Beständigkeit, kontrollierende Nachdrücklichkeit." },
  { id: "fc-sr-1.12-06", part: "Schulrecht", chapter: "1.12 Aufsichtspflicht",
    front: "Wer haftet zivilrechtlich bei Aufsichtspflichtverletzung?",
    back: "Der Dienstherr (Art. 34 GG); Regress beim Beamten nur bei Vorsatz/grober Fahrlässigkeit." },

  // ===================== 1.13 Außerunterrichtliche Veranstaltungen (AUV) =====================
  { id: "fc-sr-1.13-01", part: "Schulrecht", chapter: "1.13 Außerunterrichtliche Veranstaltungen (AUV)",
    front: "Wer genehmigt eine AUV?",
    back: "Die Schulleitung." },
  { id: "fc-sr-1.13-02", part: "Schulrecht", chapter: "1.13 Außerunterrichtliche Veranstaltungen (AUV)",
    front: "Was bedeutet \"Aufsichtspflicht rund um die Uhr\" bei mehrtägigen AUV?",
    back: "Keine schlaflosen Nächte, sondern Verhaltensregeln + ggf. Stichproben." },
  { id: "fc-sr-1.13-03", part: "Schulrecht", chapter: "1.13 Außerunterrichtliche Veranstaltungen (AUV)",
    front: "Besondere Voraussetzung der Lehrkraft bei Wasseraufenthalten?",
    back: "Rettungsfähigkeit." },
  { id: "fc-sr-1.13-04", part: "Schulrecht", chapter: "1.13 Außerunterrichtliche Veranstaltungen (AUV)",
    front: "Wer schuldet bei einer Klassenfahrt den Reisepreis?",
    back: "Schüler/Eltern – die Lehrkraft handelt nur in Stellvertretung." },
  { id: "fc-sr-1.13-05", part: "Schulrecht", chapter: "1.13 Außerunterrichtliche Veranstaltungen (AUV)",
    front: "Sind SuS bei AUV gesetzlich unfallversichert?",
    back: "Ja, immer." },

  // ===================== 1.14 Schulbezogenes Jugendrecht =====================
  { id: "fc-sr-1.14-01", part: "Schulrecht", chapter: "1.14 Schulbezogenes Jugendrecht",
    front: "Wer ist \"personensorgeberechtigt\"?",
    back: "Die Eltern oder vom Familiengericht mit dem Sorgerecht beauftragte Personen." },
  { id: "fc-sr-1.14-02", part: "Schulrecht", chapter: "1.14 Schulbezogenes Jugendrecht",
    front: "Wer ist \"erziehungsbeauftragt\"?",
    back: "Jede Person über 18, die ein Kind/Jugendlichen im Rahmen der Ausbildung betreut (auch Lehrkräfte)." },

  // ===================== 1.15 Leistungsfeststellung, Zeugnisse, Versetzung =====================
  { id: "fc-sr-1.15-01", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Welche Verordnung regelt die Leistungsfeststellung?",
    back: "Die Notenbildungsverordnung (NVO)." },
  { id: "fc-sr-1.15-02", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Mindestzahl Klassenarbeiten in Kernfächern pro Jahr?",
    back: "Mindestens 4." },
  { id: "fc-sr-1.15-03", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Höchstzahl Klassenarbeiten pro Woche?",
    back: "Höchstens 3 (an einem Tag höchstens 1, Ausnahme Nachschreiber)." },
  { id: "fc-sr-1.15-04", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Müssen schriftliche Wiederholungsarbeiten angekündigt werden?",
    back: "Nein (im Gegensatz zu Klassenarbeiten)." },
  { id: "fc-sr-1.15-05", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Was gilt für GFS?",
    back: "Zusätzliche Klassenarbeit (kein Ersatz), muss mit Kolloquium verbunden werden." },
  { id: "fc-sr-1.15-06", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Führt Nichtanfertigung von Hausaufgaben zu \"ungenügend\"?",
    back: "Nein, HA dienen nicht der Leistungsmessung (können aber Mitarbeitsnote beeinflussen)." },
  { id: "fc-sr-1.15-07", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Note bei unentschuldigtem Fehlen bei einer Leistungsmessung?",
    back: "Note 6 (ungenügend), kein Ermessen." },
  { id: "fc-sr-1.15-08", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Zeugnis vs. Halbjahresinformation – Verwaltungsakt?",
    back: "Zeugnis = Verwaltungsakt (ändert Grundverhältnis). Halbjahresinformation = kein Verwaltungsakt." },
  { id: "fc-sr-1.15-09", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Was besagt die \"KuMuTu\"-Regel?",
    back: "Bei Versetzungsgefährdung durch Kunst/Musik/Turnen zählt nur die beste Note dieser drei Fächer." },
  { id: "fc-sr-1.15-10", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "Versetzungsvoraussetzungen (Kurzformel)?",
    back: "Ø aller maßgebenden Fächer ≥ 4,0 UND Ø der Kernfächer ≥ 4,0 UND in keinem Kernfach Note 6." },
  { id: "fc-sr-1.15-11", part: "Schulrecht", chapter: "1.15 Leistungsfeststellung, Zeugnisse, Versetzung",
    front: "\"Versetzung auf Probe\" (VersO § 1 Abs. 6) – Kernpunkte?",
    back: "Nur mit Stimme des SL (Vetorecht), Nachlernzeit ca. 4 Wochen nach Sommerferien, danach Prüfung." },

  // ===================== 2.1 Grundlagen des Beamtenrechts =====================
  { id: "fc-br-2.1-01", part: "Beamtenrecht", chapter: "2.1 Grundlagen des Beamtenrechts",
    front: "Welches Gesetz regelt Laufbahn/Einstellung/Beendigung der Landesbeamten?",
    back: "Das Landesbeamtengesetz (LBG)." },
  { id: "fc-br-2.1-02", part: "Beamtenrecht", chapter: "2.1 Grundlagen des Beamtenrechts",
    front: "Was regelt das Beamtenstatusgesetz?",
    back: "Bundeseinheitlich die Statusrechte und Pflichten der Beamten." },
  { id: "fc-br-2.1-03", part: "Beamtenrecht", chapter: "2.1 Grundlagen des Beamtenrechts",
    front: "Was sind \"hoheitsrechtliche Befugnisse\"?",
    back: "Recht/Pflicht, im Namen des Staates verbindlich zu entscheiden und durchzusetzen." },
  { id: "fc-br-2.1-04", part: "Beamtenrecht", chapter: "2.1 Grundlagen des Beamtenrechts",
    front: "Wo sind die hergebrachten Grundsätze des Berufsbeamtentums verankert?",
    back: "GG Art. 33." },
  { id: "fc-br-2.1-05", part: "Beamtenrecht", chapter: "2.1 Grundlagen des Beamtenrechts",
    front: "Was ist der \"Funktionsvorbehalt\"?",
    back: "Hoheitsrechtliche Befugnisse sind im Regelfall Beamten übertragen." },
  { id: "fc-br-2.1-06", part: "Beamtenrecht", chapter: "2.1 Grundlagen des Beamtenrechts",
    front: "4 Eigenschaften des Beamten-Leitbilds?",
    back: "Unbestechlichkeit, Fachkundigkeit, Unabhängigkeit, Funktionsfähigkeit." },
  { id: "fc-br-2.1-07", part: "Beamtenrecht", chapter: "2.1 Grundlagen des Beamtenrechts",
    front: "Beamte vs. Angestellte: Begründung / Fehlverhalten / Altersversorgung / Vergütung?",
    back: "Ernennung vs. Arbeitsvertrag; Disziplinarverfahren vs. Abmahnung/Kündigung; Pension vs. Rente; Besoldungsgesetz vs. Tarifvertrag." },

  // ===================== 2.2 Arbeitszeit der Lehrkräfte =====================
  { id: "fc-br-2.2-01", part: "Beamtenrecht", chapter: "2.2 Arbeitszeit der Lehrkräfte",
    front: "Deputatsstunden einer vollen Lehrerstelle?",
    back: "25 Deputatsstunden/Woche." },
  { id: "fc-br-2.2-02", part: "Beamtenrecht", chapter: "2.2 Arbeitszeit der Lehrkräfte",
    front: "Umrechnungsfaktor Deputatsstunde → Zeitstunde?",
    back: "1,8 (25 x 1,8 = 45-Std.-Woche)." },
  { id: "fc-br-2.2-03", part: "Beamtenrecht", chapter: "2.2 Arbeitszeit der Lehrkräfte",
    front: "Gewichtung: Unterricht mit voller Vor-/Nachbereitung vs. ohne?",
    back: "1 Deputatsstunde (voll) / 0,67 (eingeschränkt) / 0,5 (keine/geringe Vor-/Nachbereitung)." },

  // ===================== 2.3 Vorgesetzte =====================
  { id: "fc-br-2.3-01", part: "Beamtenrecht", chapter: "2.3 Vorgesetzte",
    front: "Wer ist Dienstherr der Lehrkräfte in BW?",
    back: "Das Land Baden-Württemberg." },
  { id: "fc-br-2.3-02", part: "Beamtenrecht", chapter: "2.3 Vorgesetzte",
    front: "Oberste Dienstbehörde?",
    back: "Das Kultusministerium." },
  { id: "fc-br-2.3-03", part: "Beamtenrecht", chapter: "2.3 Vorgesetzte",
    front: "Dienstvorgesetzter (persönliche Angelegenheiten)?",
    back: "Das Regierungspräsidium." },
  { id: "fc-br-2.3-04", part: "Beamtenrecht", chapter: "2.3 Vorgesetzte",
    front: "Vorgesetzte für dienstliche Tätigkeit an der Schule?",
    back: "Schulleiter*in, stv. SL, Abteilungsleiter*in." },

  // ===================== 2.4 Laufbahnrecht =====================
  { id: "fc-br-2.4-01", part: "Beamtenrecht", chapter: "2.4 Laufbahnrecht",
    front: "Was besagt das Laufbahnprinzip?",
    back: "Statusrechtliche Ämter werden in Laufbahnen zusammengefasst, für die Beamte vor-/ausgebildet werden." },
  { id: "fc-br-2.4-02", part: "Beamtenrecht", chapter: "2.4 Laufbahnrecht",
    front: "Eingangsamt höherer Dienst bei Lehrkräften?",
    back: "Studienrat (StR), A13." },
  { id: "fc-br-2.4-03", part: "Beamtenrecht", chapter: "2.4 Laufbahnrecht",
    front: "Dauer Vorbereitungsdienst (Referendariat)?",
    back: "18 Monate." },
  { id: "fc-br-2.4-04", part: "Beamtenrecht", chapter: "2.4 Laufbahnrecht",
    front: "Reguläre Probezeit als \"Beamter auf Probe\"?",
    back: "In der Regel 3 Jahre (Verlängerung max. 2 J., Verkürzung 1-2 J. möglich)." },
  { id: "fc-br-2.4-05", part: "Beamtenrecht", chapter: "2.4 Laufbahnrecht",
    front: "Zeitpunkte der dienstlichen Beurteilung in der Probezeit?",
    back: "9 Monate nach Einstellung und 3 Monate vor Ende der Probezeit." },

  // ===================== 2.5 Einstellung und Entlassung =====================
  { id: "fc-br-2.5-01", part: "Beamtenrecht", chapter: "2.5 Einstellung und Entlassung",
    front: "Höchstalter für die Einstellung ins Beamtenverhältnis?",
    back: "In der Regel 42 Jahre (Ausnahmen möglich)." },
  { id: "fc-br-2.5-02", part: "Beamtenrecht", chapter: "2.5 Einstellung und Entlassung",
    front: "Folge von Täuschung/Bestechung bei der Ernennung?",
    back: "Rücknahme der Ernennung." },
  { id: "fc-br-2.5-03", part: "Beamtenrecht", chapter: "2.5 Einstellung und Entlassung",
    front: "Ab welcher Verurteilung Verlust der Beamtenrechte?",
    back: "Ab mind. 1 Jahr Freiheitsstrafe." },
  { id: "fc-br-2.5-04", part: "Beamtenrecht", chapter: "2.5 Einstellung und Entlassung",
    front: "4 Beendigungsgründe des Beamtenverhältnisses?",
    back: "Rücknahme der Ernennung, Entlassung, Verlust der Beamtenrechte, Ruhestand/Tod." },

  // ===================== 2.6 Pflichten und Rechte der Beamten =====================
  { id: "fc-br-2.6-01", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "3 Bereiche der Beamtenpflichten?",
    back: "Dienstleistungspflichten, Treuepflichten, Verhaltenspflichten." },
  { id: "fc-br-2.6-02", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "3 Bereiche der Beamtenrechte?",
    back: "Vermögenswerte Rechte, Fürsorgerechte, Schutzrechte." },
  { id: "fc-br-2.6-03", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "Was ist die Remonstrationspflicht?",
    back: "Pflicht/Recht, bei Rechtmäßigkeitsbedenken gegen eine Dienstanweisung Widerspruch einzulegen." },
  { id: "fc-br-2.6-04", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "Wertgrenze für Geschenke von Einzelpersonen an Lehrkräfte?",
    back: "5 Euro (bei Gruppengeschenken höher)." },
  { id: "fc-br-2.6-05", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "Überwältigungsverbot vs. Kontroversitätsgebot (Beutelsbacher Konsens)?",
    back: "Überwältigungsverbot: kein Indoktrinieren mit eigener Meinung. Kontroversitätsgebot: kontroverse Themen auch kontrovers unterrichten." },
  { id: "fc-br-2.6-06", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "Dürfen Beamte Parteimitglied werden?",
    back: "Ja, solange die Partei nicht verfassungswidrig ist." },
  { id: "fc-br-2.6-07", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "Ist ein Kopftuch bei Lehrkräften generell verboten?",
    back: "Nein, Einzelfallprüfung (Verbot nur bei Gefährdung des Schulfriedens); Vollverschleierung ist die Grenze." },
  { id: "fc-br-2.6-08", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "Was umfasst die Amtsverschwiegenheit an der Schule besonders?",
    back: "Das Konferenzgeheimnis." },
  { id: "fc-br-2.6-09", part: "Beamtenrecht", chapter: "2.6 Pflichten und Rechte der Beamten",
    front: "Dürfen Lehrkräfte ihre eigenen Kinder unterrichten?",
    back: "Nein – Grundsatz der Unparteilichkeit." },

  // ===================== 2.7 Personalvertretung =====================
  { id: "fc-br-2.7-01", part: "Beamtenrecht", chapter: "2.7 Personalvertretung",
    front: "Personalvertretung auf KM- / RP- / Schulebene?",
    back: "HPR (Hauptpersonalrat) / BPR (Bezirkspersonalrat) / ÖPR (örtlicher Personalrat)." },
  { id: "fc-br-2.7-02", part: "Beamtenrecht", chapter: "2.7 Personalvertretung",
    front: "3 Stufen der Beteiligungsrechte des Personalrats?",
    back: "Anhörung < Mitwirkung < Mitbestimmung (stärkste Form)." },
  { id: "fc-br-2.7-03", part: "Beamtenrecht", chapter: "2.7 Personalvertretung",
    front: "Wodurch ist die Personalvertretung begrenzt?",
    back: "Durch den Amtsauftrag der Behörde und das Demokratieprinzip." },

  // ===================== 2.8 Pflichtverletzung: Dienstvergehen =====================
  { id: "fc-br-2.8-01", part: "Beamtenrecht", chapter: "2.8 Pflichtverletzung: Dienstvergehen von Beamten",
    front: "Was ist ein Dienstvergehen?",
    back: "Eine schuldhafte (vorsätzliche/fahrlässige) Pflichtverletzung – auch außerdienstlich möglich, wenn es dem Ansehen des Beamtentums schadet." },
  { id: "fc-br-2.8-02", part: "Beamtenrecht", chapter: "2.8 Pflichtverletzung: Dienstvergehen von Beamten",
    front: "Welches Gesetz regelt das Disziplinarverfahren?",
    back: "Das Landesdisziplinargesetz." },
  { id: "fc-br-2.8-03", part: "Beamtenrecht", chapter: "2.8 Pflichtverletzung: Dienstvergehen von Beamten",
    front: "Zuständige Behörde für Disziplinarverfahren gegen Lehrkräfte?",
    back: "Die Schulaufsicht." },
  { id: "fc-br-2.8-04", part: "Beamtenrecht", chapter: "2.8 Pflichtverletzung: Dienstvergehen von Beamten",
    front: "Mildeste Reaktion des Schulleiters unterhalb einer Disziplinarmaßnahme?",
    back: "Die Missbilligung." },
  { id: "fc-br-2.8-05", part: "Beamtenrecht", chapter: "2.8 Pflichtverletzung: Dienstvergehen von Beamten",
    front: "Was ist eine \"Spannungsversetzung\"?",
    back: "Versetzung bei ungelöstem, den Schulfrieden störendem Lehrkräftestreit nach gescheiterter Mediation." },
  { id: "fc-br-2.8-06", part: "Beamtenrecht", chapter: "2.8 Pflichtverletzung: Dienstvergehen von Beamten",
    front: "Kann eine Pflichtverletzung disziplinar- UND strafrechtlich geahndet werden?",
    back: "Ja (\"Doppelbestrafung\" möglich, z.B. Körperverletzung im Amt)." },

  // ===================== 2.9 Rechtsstellung der Referendare =====================
  { id: "fc-br-2.9-01", part: "Beamtenrecht", chapter: "2.9 Rechtsstellung der Referendare",
    front: "Beamtenstatus von Referendaren?",
    back: "Beamte auf Widerruf." },
  { id: "fc-br-2.9-02", part: "Beamtenrecht", chapter: "2.9 Rechtsstellung der Referendare",
    front: "Wann enden Vorbereitungsdienst und Beamtenverhältnis kraft Gesetzes?",
    back: "Mit Ablauf des Tages der Mitteilung des Bestehens/wiederholten Nichtbestehens der Prüfung." },
  { id: "fc-br-2.9-03", part: "Beamtenrecht", chapter: "2.9 Rechtsstellung der Referendare",
    front: "Max. vergütbare zusätzliche Unterrichtsstunden/Monat bei dringendem Bedarf?",
    back: "Bis zu 24 Std./Monat." },
  { id: "fc-br-2.9-04", part: "Beamtenrecht", chapter: "2.9 Rechtsstellung der Referendare",
    front: "Folge bei unerlaubtem Versäumen von Seminarveranstaltungen?",
    back: "Anteiliger Verlust der Bezüge." },
  { id: "fc-br-2.9-05", part: "Beamtenrecht", chapter: "2.9 Rechtsstellung der Referendare",
    front: "Ab welcher Verlängerung droht vorzeitige Entlassung?",
    back: "Bei erforderlicher Verlängerung um mehr als 2 Unterrichtshalbjahre." }

];
